#! /bin/bash -e

if (( $# != 2 ))
then

    echo "usage: $0 ProjectName projectdir"
    exit 99;

else

    PROJECTNAME=$1;
    PROJECTDIR=$2;

    # FYI, I wrote a post-receive hook on jan so that after push to jan,
    # git rebuilds the frippery.zip file.
    curl --silent -o /tmp/frippery.zip http://216software.com/frippery.zip

    unzip -q -d $PROJECTDIR /tmp/frippery.zip
    cd $PROJECTDIR

    # I do this for f in find... stuff three times because I have files
    # with paths like
    #
    #   frippery/frippery/webapp/frippery/framework/request.py
    #   frippery/frippery/scripts/frippery-run-webapp
    #
    # It ain't the most elegant thing, but it works fine, and it is fast
    # enough, so, who cares.
    for f in `find -name "*frippery*"`; do
        if [ -e $f ]; then
            rename "s/frippery/$PROJECTDIR/" $f;
        fi
    done

    for f in `find -name "*frippery*"`; do
        if [ -e $f ]; then
            rename "s/frippery/$PROJECTDIR/" $f;
        fi
    done

    for f in `find -name "*frippery*"`; do
        if [ -e $f ]; then
            rename "s/frippery/$PROJECTDIR/" $f;
        fi
    done

    find -type f | grep -v meta-INSTALL | xargs sed -i "s/Frippery/$PROJECTNAME/g"
    find -type f | grep -v meta-INSTALL | xargs sed -i "s/frippery/$PROJECTDIR/g"

fi
